<#macro profileEdit>
    <div class="profile-edit-background hide" id="profile-edit-background">
        <div class="profile-edit-block">
            <div class="profile-edit-block-title">Редактировать данные</div>
            <button class="btn2" type="submit" form="userEditForm">Сохранить</button>
            <button class="btn2" onclick="hideBlock('profile-edit-background')">Закрыть</button>
        </div>
    </div>
</#macro>